name: TEST

on: 
    push:
    pull_request: 
    workflow_dispatch:
        inputs:
            input_one:
                type: string
            input_two:
                type: string

jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - run: echo "HELLO WORLD"
    say-hola:
        needs: say-hello
        runs-on: ubuntu-latest

        steps:
            - run: echo "HOLA WORLD"
